#1
install.packages("arules")
install.packages("arulesViz")
library(arules)
library(arulesViz)
myData <- read.transactions("C:/Users/cdub4/Downloads/Ch14_Q48_Data_File_CSV.csv", format = "basket", sep = ",")
inspect(myData[1:5])
itemFrequency(myData)
itemFrequencyPlot(myData)
rules <- apriori(myData, parameter = list(minlen = 2, supp=.1, conf=.5))
srules <- sort(rules, by = 'lift', decreasing = TRUE)
inspect(srules)
plot(rules)
#2
myData <- read.transactions("C:/Users/cdub4/Downloads/Ch14_Q63_Data_File.csv", format = "basket", sep = ",")
inspect(myData[1:5])
itemFrequency(myData)
itemFrequencyPlot(myData)
rules <- apriori(myData, parameter = list(minlen = 2, supp=.01, conf=.25))
srules <- sort(rules, by = 'lift', decreasing = TRUE)
inspect(srules)
plot(rules)
